using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Bevy.Generator;

/// <summary>Writes the C# source for a behavior's runner and the per-assembly registration.</summary>
internal static class BehaviorEmitter
{
    private const string Header =
        "// <auto-generated by BevyCSharp.Generator />\n"
        + "#nullable enable\n"
        + "#pragma warning disable CS1591\n";

    /// <summary>Emits the runner class for one behavior.</summary>
    internal static string Emit(BehaviorModel model)
    {
        var source = new StringBuilder(Header);

        if (model.Namespace is not null)
            source.Append("\nnamespace ").Append(model.Namespace).Append(";\n");

        source.Append('\n')
            .Append("/// <summary>Generated Bevy systems for <see cref=\"")
            .Append(model.Name).Append("\"/>.</summary>\n")
            .Append("internal static class ").Append(model.RunnerName).Append('\n')
            .Append("{\n");

        EmitRegister(source, model);

        foreach (var method in model.Methods)
        {
            source.Append('\n');
            if (method.IsStatic)
                EmitStaticSystem(source, model, method);
            else
                EmitInstanceSystem(source, model, method);
        }

        source.Append("}\n");
        return source.ToString();
    }

    /// <summary>Emits <c>Register(App)</c>, adding one descriptor per method.</summary>
    private static void EmitRegister(StringBuilder source, BehaviorModel model)
    {
        source.Append("    /// <summary>Adds every system on this behavior to the schedule.</summary>\n")
            .Append("    internal static void Register(global::Bevy.App app)\n")
            .Append("    {\n");

        foreach (var method in model.Methods)
        {
            var systemId = SystemId(model, method);

            source.Append("        app.AddSystem(global::Bevy.Stage.")
                .Append(method.Stage).Append(", new global::Bevy.SystemDescriptor(")
                .Append(SystemMethodName(model, method))
                .Append(", \"").Append(systemId).Append("\")");

            // A [ToggleKey] is itself a run condition, so the two are mutually exclusive;
            // the toggle wins because it is the more specific declaration.
            if (method.Toggle is { } toggle)
            {
                // The modifier argument is already a folded flags constant, so a combination such
                // as Ctrl | Shift emits as one cast and needs no special handling.
                source.Append("\n            .RunIf(global::Bevy.BehaviorConditions.KeyToggle(\"")
                    .Append(systemId).Append("\", (global::Bevy.Key)").Append(toggle.Key)
                    .Append(", (global::Bevy.KeyModifier)").Append(toggle.Modifiers)
                    .Append(", ").Append(toggle.DefaultEnabled ? "true" : "false").Append("))");
            }
            else if (method.Condition is { } condition)
            {
                source.Append("\n            .RunIf(").Append(ConditionExpression(model, condition)).Append(')');
            }

            // Access metadata: an instance method writes its own component store, a static one
            // only declares a read of the world. Keeping these distinct is what lets unrelated
            // behaviors be reported as non-conflicting.
            source.Append(method.IsStatic
                ? "\n            .Read<global::Bevy.EcsWorld>()"
                : $"\n            .Write<{model.QualifiedName}>()");

            source.Append(");\n");
        }

        source.Append("    }\n");
    }

    /// <summary>Emits a system that calls a static behavior method once per frame.</summary>
    private static void EmitStaticSystem(StringBuilder source, BehaviorModel model, StageMethod method)
    {
        source.Append("    private static void ").Append(SystemMethodName(model, method))
            .Append("(global::Bevy.World world)\n")
            .Append("    {\n")
            .Append("        ").Append(model.QualifiedName).Append('.').Append(method.Name)
            .Append("(new global::Bevy.BehaviorContext(world));\n")
            .Append("    }\n");
    }

    /// <summary>
    /// Emits a system that calls an instance behavior method once per matching entity.
    /// </summary>
    /// <remarks>
    /// The loop itself is <c>BehaviorRunners.Run</c>'s job. All this method contributes is the
    /// filter component ids and a lambda that forwards to the user's method with <c>this</c>
    /// bound by reference, so writes land in Bevy's storage rather than in a copy.
    /// </remarks>
    private static void EmitInstanceSystem(StringBuilder source, BehaviorModel model, StageMethod method)
    {
        source.Append("    private static void ").Append(SystemMethodName(model, method))
            .Append("(global::Bevy.World world)\n")
            .Append("    {\n");

        EmitFilterIds(source, "__with", method.Filters.With);
        EmitFilterIds(source, "__without", method.Filters.Without);
        EmitFilterIds(source, "__changed", method.Filters.Changed);

        source.Append("        global::Bevy.BehaviorRunners.Run<").Append(model.QualifiedName)
            .Append(">(\n")
            .Append("            world,\n")
            .Append("            static (ref ").Append(model.QualifiedName)
            .Append(" __behavior, global::Bevy.Entity __entity, global::Bevy.BehaviorContext __context) =>\n")
            .Append("                __behavior.").Append(method.Name).Append("(__context),\n")
            .Append("            __with,\n")
            .Append("            __without,\n")
            .Append("            __changed);\n")
            .Append("    }\n");
    }

    /// <summary>
    /// Emits the component-id array for one filter kind.
    /// </summary>
    /// <remarks>
    /// Ids are resolved per call rather than cached in a static, because they belong to a
    /// specific world: caching them would hand stale ids to a second <c>App</c>. The lookup is
    /// a generic static field read, which the JIT reduces to almost nothing.
    /// </remarks>
    private static void EmitFilterIds(StringBuilder source, string name, IReadOnlyList<string> types)
    {
        if (types.Count == 0)
        {
            source.Append("        global::System.ReadOnlySpan<int> ").Append(name)
                .Append(" = default;\n");
            return;
        }

        source.Append("        global::System.Span<int> ").Append(name)
            .Append(" = stackalloc int[] { ");

        for (var i = 0; i < types.Count; i++)
        {
            if (i > 0) source.Append(", ");
            source.Append("global::Bevy.EcsWorld.ComponentId<").Append(types[i]).Append(">()");
        }

        source.Append(" };\n");
    }

    /// <summary>Builds the expression a <c>[RunIf]</c> condition compiles down to.</summary>
    private static string ConditionExpression(BehaviorModel model, ConditionInfo condition) =>
        condition.Kind == ConditionKind.Method
            // A condition method already has the (World) -> bool shape a run condition needs.
            ? $"{model.QualifiedName}.{condition.MemberName}"
            // A field or property has no parameter, so it is wrapped in one.
            : $"static _ => {model.QualifiedName}.{condition.MemberName}";

    /// <summary>The stable identifier a system is registered and toggled under.</summary>
    private static string SystemId(BehaviorModel model, StageMethod method) =>
        $"{model.Name}.{method.Name}";

    /// <summary>The name of the generated system method for one stage method.</summary>
    private static string SystemMethodName(BehaviorModel model, StageMethod method) =>
        $"Run_{method.Name}_{method.Stage}";

    /// <summary>
    /// Emits the single per-assembly entry point that registers every behavior found.
    /// </summary>
    /// <remarks>
    /// The class is internal, so each assembly gets its own copy of this name without colliding
    /// with any other assembly's. BehaviorsPlugin finds them all by attribute, not by name.
    /// </remarks>
    internal static string EmitRegistration(IReadOnlyList<BehaviorModel> models)
    {
        var source = new StringBuilder(Header);

        source.Append("\nnamespace Bevy.Generated;\n\n")
            .Append("/// <summary>Registers every [Behavior] struct in this assembly.</summary>\n")
            .Append("internal static class BehaviorRegistration\n")
            .Append("{\n")
            .Append("    /// <summary>\n")
            .Append("    /// Announces this assembly's behaviors as soon as the CLR touches it, so an app\n")
            .Append("    /// can find them without scanning, which also keeps them safe from trimming.\n")
            .Append("    /// </summary>\n")
            .Append("    [global::System.Runtime.CompilerServices.ModuleInitializer]\n")
            .Append("    internal static void Initialize()\n")
            .Append("        => global::Bevy.BehaviorRegistry.Add(Register);\n\n")
            .Append("    /// <summary>Adds every behavior in this assembly to <paramref name=\"app\"/>.</summary>\n")
            .Append("    [global::Bevy.GeneratedBehaviorRegistration]\n")
            .Append("    internal static void Register(global::Bevy.App app)\n")
            .Append("    {\n");

        foreach (var model in models.OrderBy(m => m.QualifiedName, System.StringComparer.Ordinal))
        {
            source.Append("        global::");
            if (model.Namespace is not null) source.Append(model.Namespace).Append('.');
            source.Append(model.RunnerName).Append(".Register(app);\n");
        }

        source.Append("    }\n").Append("}\n");
        return source.ToString();
    }
}
