using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Bevy.Generator;

/// <summary>
/// Turns the checked-in list of Bevy's components that moved into the former paths a reflected
/// component's schema is found by.
/// </summary>
/// <remarks>
/// <para>
/// A reflected component's schema is built while the app runs, from Bevy's registry, which knows
/// only where a type is now. A scene names a component by the path it had when the scene was
/// written, so one written before Bevy moved a type names a path the registry no longer has, and
/// the component would be refused. The list gives each moved type the paths it had, and the
/// schema keeps them as the former names a generated schema keeps from a <c>[FormerName]</c>.
/// </para>
/// <para>
/// The list is <c>bevy-former-paths.tsv</c> beside <c>bevy-components.tsv</c>, which the
/// <c>schema.dump</c> command writes again at every upgrade and so cannot carry what a type was,
/// and it is named as an additional file by the library alone, as that one is.
/// </para>
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class FormerPathsGenerator : IIncrementalGenerator
{
    private const string FileName = "bevy-former-paths.tsv";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var moves = context.AdditionalTextsProvider
            .Where(static file =>
                file.Path.EndsWith("/" + FileName, StringComparison.Ordinal)
                || file.Path.EndsWith("\\" + FileName, StringComparison.Ordinal)
                || file.Path == FileName)
            .Select(static (file, token) => Parse(file.GetText(token)?.ToString() ?? string.Empty));

        context.RegisterSourceOutput(moves, static (spc, list) => spc.AddSource("ReflectedFormerPaths.g.cs", Emit(list)));
    }

    /// <summary>Each move's former path and the path it moved to, in the file's order.</summary>
    private static EquatableArray<string> Parse(string text)
    {
        var pairs = new List<string>();
        foreach (var line in text.Split('\n'))
        {
            var columns = line.TrimEnd('\r').Split('\t');
            if (columns.Length >= 3 && columns[0] == "former")
            {
                pairs.Add(columns[1]);
                pairs.Add(columns[2]);
            }
        }

        return new EquatableArray<string>(pairs.ToArray());
    }

    private static string Emit(EquatableArray<string> list)
    {
        var former = new Dictionary<string, List<string>>(StringComparer.Ordinal);
        for (var i = 0; i + 1 < list.Items.Count; i += 2)
        {
            if (!former.TryGetValue(list.Items[i + 1], out var paths)) former[list.Items[i + 1]] = paths = new List<string>();
            paths.Add(list.Items[i]);
        }

        var source = new StringBuilder();
        source.Append("// <auto-generated/>\n#nullable enable\nnamespace Bevy;\n\n");
        source.Append("/// <summary>The paths Bevy's moved components had, generated from <c>bevy-former-paths.tsv</c>.</summary>\n");
        source.Append("internal static class ReflectedFormerPaths\n{\n");
        source.Append("    /// <summary>The paths the component at <paramref name=\"path\"/> had before it moved, or none.</summary>\n");
        source.Append("    internal static string[] Of(string path) => path switch\n    {\n");
        foreach (var pair in former.OrderBy(p => p.Key, StringComparer.Ordinal))
        {
            source.Append("        \"").Append(pair.Key).Append("\" => [")
                .Append(string.Join(", ", pair.Value.Select(p => "\"" + p + "\"")))
                .Append("],\n");
        }

        source.Append("        _ => [],\n    };\n}\n");
        return source.ToString();
    }
}
