using System.Collections.Generic;
using System.Text;

namespace Bevy.Generator;

/// <summary>
/// Writes the wiring between a panel class, its document and its elements.
/// </summary>
/// <remarks>
/// The emitted code stays thin, the way the behavior runners do. Every read and write goes
/// through <c>PanelBinding</c> in the editor's framework, so the generated file is a list of
/// calls a person can read and step through, and changing how a binding behaves is changing that
/// class rather than regenerating anyone's panel.
/// </remarks>
internal static class PanelEmitter
{
    private const string Header =
        "// <auto-generated/>\n"
        + "#nullable enable\n";

    /// <summary>Emits the partial half of one panel.</summary>
    internal static string Emit(PanelModel model)
    {
        var source = new StringBuilder(Header);

        if (model.Namespace is not null)
            source.Append("\nnamespace ").Append(model.Namespace).Append(";\n");

        source.Append("\npartial class ").Append(model.Name)
            .Append(" : global::BevyCSharp.Editor.Framework.IEditorPanel\n{\n");

        source.Append("    /// <summary>The window this panel is showing in.</summary>\n")
            .Append("    public global::BevyCSharp.Editor.Framework.EditorWindow? Window ")
            .Append("{ get; private set; }\n\n");

        source.Append("    /// <summary>Opens the panel's document.</summary>\n")
            .Append("    public void Open() => Window = ")
            .Append("global::BevyCSharp.Editor.Framework.EditorWindow.Open(\"")
            .Append(model.Document).Append("\");\n\n");

        source.Append("    /// <summary>Closes it again.</summary>\n")
            .Append("    public void Close()\n    {\n")
            .Append("        Window?.Close();\n")
            .Append("        Window = null;\n")
            .Append("    }\n\n");

        EmitPull(source, model);
        EmitPush(source, model);
        EmitInvoke(source, model);

        source.Append("}\n");
        return source.ToString();
    }

    /// <summary>Writes the panel's values out to its elements.</summary>
    private static void EmitPull(StringBuilder source, PanelModel model)
    {
        source.Append("    /// <summary>Writes this panel's values out to its elements.</summary>\n")
            .Append("    public void Pull()\n    {\n")
            .Append("        if (Window is not { IsOpen: true } window) return;\n");

        foreach (var binding in model.Bindings)
        {
            source.Append("\n        global::BevyCSharp.Editor.Framework.PanelBinding.Pull")
                .Append(binding.Kind).Append("(window.Element(\"").Append(binding.Element)
                .Append("\"), ");

            if (binding.Kind == BindKind.Number) source.Append("(float)");
            source.Append(binding.Member).Append(");\n");
        }

        source.Append("    }\n\n");
    }

    /// <summary>Reads one element back into the panel.</summary>
    private static void EmitPush(StringBuilder source, PanelModel model)
    {
        source.Append("    /// <summary>Reads one element back into this panel.</summary>\n")
            .Append("    public bool Push(global::Bevy.Entity element)\n    {\n")
            .Append("        if (Window is not { IsOpen: true } window) return false;\n");

        foreach (var binding in model.Bindings)
        {
            // A one way binding still claims its element, so no other panel is asked about it.
            source.Append("\n        if (element == window.Element(\"").Append(binding.Element)
                .Append("\"))\n        {\n");

            if (binding.TwoWay)
            {
                source.Append("            ").Append(binding.Member).Append(" = ");

                if (binding.Kind == BindKind.Number && binding.NumericType != "float")
                    source.Append('(').Append(binding.NumericType).Append(')');

                source.Append("global::BevyCSharp.Editor.Framework.PanelBinding.Push")
                    .Append(binding.Kind).Append("(element, ");

                if (binding.Kind == BindKind.Number) source.Append("(float)");
                source.Append(binding.Member).Append(");\n");
            }

            source.Append("            return true;\n        }\n");
        }

        source.Append("\n        return false;\n    }\n\n");
    }

    /// <summary>Runs whatever a click is bound to.</summary>
    private static void EmitInvoke(StringBuilder source, PanelModel model)
    {
        source.Append("    /// <summary>Runs whatever a click on an element is bound to.</summary>\n")
            .Append("    public bool Invoke(global::Bevy.Entity element)\n    {\n")
            .Append("        if (Window is not { IsOpen: true } window) return false;\n");

        foreach (var command in model.Commands)
        {
            source.Append("\n        if (element == window.Element(\"").Append(command.Element)
                .Append("\"))\n        {\n")
                .Append("            ").Append(command.Method).Append("();\n")
                .Append("            return true;\n        }\n");
        }

        source.Append("\n        return false;\n    }\n");
    }

    /// <summary>
    /// Emits the single per-assembly list of the panels found.
    /// </summary>
    /// <remarks>
    /// Panels are constructed by whoever shows them, unlike behaviors, because a panel usually
    /// needs something to bind against. This is a catalogue rather than a registration: it says
    /// what exists and where its document is, so a shell can offer them without naming each one.
    /// </remarks>
    internal static string EmitCatalogue(IReadOnlyList<PanelModel> models)
    {
        var source = new StringBuilder(Header);

        source.Append("\nnamespace Bevy.Generated;\n\n")
            .Append("/// <summary>Every [EditorPanel] class in this assembly.</summary>\n")
            .Append("internal static class PanelCatalogue\n{\n")
            .Append("    /// <summary>Each panel's type and the document it opens.</summary>\n")
            .Append("    internal static readonly (global::System.Type Panel, string Document)[] All =\n")
            .Append("    [\n");

        foreach (var model in models)
        {
            source.Append("        (typeof(global::").Append(model.QualifiedName)
                .Append("), \"").Append(model.Document).Append("\"),\n");
        }

        source.Append("    ];\n}\n");
        return source.ToString();
    }
}
