using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Bevy.Generator;

/// <summary>
/// Writes the field tables that let a tool show a component it has never heard of.
/// </summary>
/// <remarks>
/// <para>
/// The bridge answers what an entity carries in component ids, and can name one, but a name is
/// not enough to draw a row: that needs the fields, their types, and a way to read and write
/// them. None of that has to cross the ABI, because a <c>[Behavior]</c> struct is a C# type this
/// generator is already reading. So the field table is emitted here, beside the runner, and the
/// engine stays out of it entirely.
/// </para>
/// <para>
/// Accessors rather than byte offsets: the emitted closure reads and writes the real struct
/// through the ordinary typed API, which means the runtime's own layout decisions cannot be got
/// wrong, and change detection fires exactly as it would for a behavior writing its own field.
/// </para>
/// </remarks>
internal static class SchemaEmitter
{
    private const string Header =
        "// <auto-generated by BevyCSharp.Generator />\n"
        + "#nullable enable\n"
        + "#pragma warning disable CS1591\n";

    /// <summary>Emits the per-assembly schema registration, or null when there is nothing to say.</summary>
    internal static string? Emit(IReadOnlyList<BehaviorModel> models)
    {
        var described = models
            .Where(model => model.Fields.Count > 0)
            .OrderBy(model => model.QualifiedName, System.StringComparer.Ordinal)
            .ToList();

        if (described.Count == 0) return null;

        var source = new StringBuilder(Header)
            .Append("\nnamespace Bevy.Generated;\n\n")
            .Append("/// <summary>Describes this assembly's behaviors to anything inspecting them.</summary>\n")
            .Append("internal static class ComponentSchemaRegistration\n")
            .Append("{\n")
            .Append("    /// <summary>\n")
            .Append("    /// Registers the field tables as soon as the CLR touches this assembly, so a\n")
            .Append("    /// tool can describe a component without the assembly having been asked to.\n")
            .Append("    /// </summary>\n")
            .Append("    [global::System.Runtime.CompilerServices.ModuleInitializer]\n")
            .Append("    internal static void Initialize()\n")
            .Append("    {\n");

        foreach (var model in described)
        {
            source.Append("        global::Bevy.ComponentSchemas.Add(")
                .Append(SchemaMethodName(model)).Append("());\n");
        }

        source.Append("    }\n");

        foreach (var model in described)
        {
            source.Append('\n');
            EmitSchema(source, model);
        }

        source.Append("}\n");
        return source.ToString();
    }

    /// <summary>Emits the factory for one behavior's schema.</summary>
    private static void EmitSchema(StringBuilder source, BehaviorModel model)
    {
        source.Append("    /// <summary>The fields of <see cref=\"").Append(model.QualifiedName)
            .Append("\"/>.</summary>\n")
            .Append("    private static global::Bevy.ComponentSchema ")
            .Append(SchemaMethodName(model)).Append("()\n")
            .Append("        => new(\n")
            .Append("            \"").Append(model.Name).Append("\",\n")
            .Append("            \"").Append(FullName(model)).Append("\",\n")
            .Append("            static () => global::Bevy.ComponentType<")
            .Append(model.QualifiedName).Append(">.Id,\n")
            .Append("            [\n");

        foreach (var field in model.Fields)
            EmitField(source, model, field);

        source.Append("            ],\n");

        EmitMethods(source, model);

        // Adding writes a default value, which for a blittable struct is its zeroed bytes, and
        // that is what a component the person just asked for should start as.
        source.Append("            add: static (world, entity) =>\n")
            .Append("                world.Add(entity, default(").Append(model.QualifiedName)
            .Append(")),\n")
            .Append("            remove: static (world, entity) =>\n")
            .Append("                world.Remove<").Append(model.QualifiedName).Append(">(entity));\n");
    }

    /// <summary>Emits the list of methods a tool can offer as buttons.</summary>
    /// <remarks>
    /// Read, call, write back. The method may change the component, and going through the ordinary
    /// value API rather than a reference into storage is what makes Bevy see that it did.
    /// </remarks>
    private static void EmitMethods(StringBuilder source, BehaviorModel model)
    {
        if (model.Invokables.Count == 0)
        {
            source.Append("            [],\n");
            return;
        }

        source.Append("            [\n");

        foreach (var method in model.Invokables)
        {
            source.Append("                new(\n")
                .Append("                    \"").Append(method.Name).Append("\",\n")
                .Append("                    static (world, entity) =>\n")
                .Append("                    {\n")
                .Append("                        if (!world.TryGet<").Append(model.QualifiedName)
                .Append(">(entity, out var component)) return;\n\n")
                .Append("                        component.").Append(method.Name).Append("();\n")
                .Append("                        world.Set(entity, component);\n")
                .Append("                    })");

            EmitMethodHints(source, method.Hints);
            source.Append(",\n");
        }

        source.Append("            ],\n");
    }

    /// <summary>Emits one field, with the pair of closures that reach the live component.</summary>
    private static void EmitField(StringBuilder source, BehaviorModel model, BehaviorField field)
    {
        source.Append("                new(\n")
            .Append("                    \"").Append(field.Name).Append("\",\n")
            .Append("                    global::Bevy.FieldKind.").Append(field.Kind).Append(",\n")
            .Append("                    \"").Append(Display(field.Type)).Append("\",\n")
            // Read: absent component reads as null, which is what a tool draws as a blank row
            // rather than as a zero it might then write back.
            .Append("                    static (world, entity) =>\n")
            .Append("                        world.TryGet<").Append(model.QualifiedName)
            .Append(">(entity, out var component) ? component.").Append(field.Name)
            .Append(" : null")
            // Write: read, modify, write back. Going through Set rather than a reference into
            // storage is what makes Bevy see the change.
            .Append(Writer(model, field));

        var hints = field.Hints.IsEmpty ? null : field.Hints;

        if (field.Options.Items.Count > 0 || hints is not null)
        {
            source.Append(",\n                    [");
            var first = true;
            foreach (var option in field.Options.Items)
            {
                if (!first) source.Append(", ");
                source.Append('"').Append(option).Append('"');
                first = false;
            }

            source.Append(']');
        }

        if (hints is not null) EmitHints(source, hints);

        source.Append("),\n");
    }

    /// <summary>Emits what a field's attributes asked for, as the record a tool reads.</summary>
    /// <remarks>
    /// Named arguments throughout, so a hint added to the record later does not shift the meaning
    /// of what is emitted here.
    /// </remarks>
    private static void EmitHints(StringBuilder source, FieldHintModel hints)
    {
        source.Append(",\n                    new global::Bevy.FieldHints(\n");

        var parts = new List<string>();
        if (hints.Label is not null) parts.Add("Label: " + Quote(hints.Label));
        if (hints.Tooltip is not null) parts.Add("Tooltip: " + Quote(hints.Tooltip));
        if (hints.Header is not null) parts.Add("Header: " + Quote(hints.Header));
        if (hints.Unit is not null) parts.Add("Unit: " + Quote(hints.Unit));
        if (hints.Minimum is not null) parts.Add("Minimum: " + Literal(hints.Minimum.Value));
        if (hints.Maximum is not null) parts.Add("Maximum: " + Literal(hints.Maximum.Value));
        if (hints.Step is not null) parts.Add("Step: " + Literal(hints.Step.Value));
        if (hints.Readout is not null)
            parts.Add("Readout: global::Bevy.SliderReadout." + hints.Readout);

        if (hints.ReadOnly) parts.Add("ReadOnly: true");
        if (hints.Hidden) parts.Add("Hidden: true");
        if (hints.Space) parts.Add("Space: true");
        if (hints.Separator) parts.Add("Separator: true");
        if (hints.Colour) parts.Add("Colour: true");
        if (hints.Wide) parts.Add("Wide: true");
        if (hints.Inline) parts.Add("Inline: true");
        if (hints.Foldout is not null) parts.Add("Foldout: " + Quote(hints.Foldout));
        if (hints.FoldoutShut) parts.Add("FoldoutOpen: false");
        if (hints.Note is not null) parts.Add("Note: " + Quote(hints.Note));

        if (hints.NoteKind is not null)
            parts.Add("NoteKind: global::Bevy.NoteKind." + hints.NoteKind);

        if (hints.Conditions.Items.Count > 0) parts.Add(Conditions(hints.Conditions));
        if (hints.Changed.Items.Count > 0) parts.Add(Changed(hints.Changed));
        if (hints.Order != 0) parts.Add("Order: " + hints.Order.ToString(Invariant));
        if (hints.Asset is not null) parts.Add("Asset: " + Quote(hints.Asset));
        if (hints.Extensions is not null) parts.Add("Extensions: " + Quote(hints.Extensions));

        for (var i = 0; i < parts.Count; i++)
        {
            source.Append("                        ").Append(parts[i]);
            if (i < parts.Count - 1) source.Append(',');
            source.Append('\n');
        }

        source.Append("                    )");
    }

    /// <summary>What has to hold for a field to be shown, as an array of conditions.</summary>
    private static string Conditions(EquatableArray<ConditionModel> conditions)
    {
        var written = conditions.Items.Select(condition =>
            "new global::Bevy.FieldCondition("
            + Quote(condition.Field)
            + ", " + (condition.Value is null ? "null" : Quote(condition.Value))
            + (condition.Not ? ", true" : string.Empty)
            + ")");

        return "Conditions: [" + string.Join(", ", written) + "]";
    }

    /// <summary>The methods to call once a field has been changed.</summary>
    private static string Changed(EquatableArray<string> methods) =>
        "Changed: [" + string.Join(", ", methods.Items.Select(Quote)) + "]";

    /// <summary>The one culture a generator may write numbers in.</summary>
    private static readonly System.Globalization.CultureInfo Invariant =
        System.Globalization.CultureInfo.InvariantCulture;

    /// <summary>A number as C# source.</summary>
    private static string Literal(double value) => value.ToString("R", Invariant) + "d";

    /// <summary>A string as C# source.</summary>
    private static string Quote(string text) =>
        "\"" + text.Replace("\\", "\\\\").Replace("\"", "\\\"") + "\"";

    /// <summary>Emits what a method's attributes asked for, when they asked for anything.</summary>
    private static void EmitMethodHints(StringBuilder source, MethodHintModel hints)
    {
        if (hints.IsEmpty) return;

        var parts = new List<string>();
        if (hints.Label is not null) parts.Add("Label: " + Quote(hints.Label));
        if (hints.Tooltip is not null) parts.Add("Tooltip: " + Quote(hints.Tooltip));
        if (hints.Hidden) parts.Add("Hidden: true");

        if (hints.Line is not null) parts.Add("Line: global::Bevy.ButtonLine." + hints.Line);

        if (hints.Weight is not 1d) parts.Add("Weight: " + Literal(hints.Weight));
        if (hints.Space) parts.Add("Space: true");
        if (hints.Separator) parts.Add("Separator: true");
        if (hints.Header is not null) parts.Add("Header: " + Quote(hints.Header));
        if (hints.Foldout is not null) parts.Add("Foldout: " + Quote(hints.Foldout));
        if (hints.FoldoutShut) parts.Add("FoldoutOpen: false");
        if (hints.Note is not null) parts.Add("Note: " + Quote(hints.Note));

        if (hints.NoteKind is not null)
            parts.Add("NoteKind: global::Bevy.NoteKind." + hints.NoteKind);

        if (hints.Order != 0) parts.Add("Order: " + hints.Order.ToString(Invariant));

        source.Append("\n                {\n                    Hints = new global::Bevy.MethodHints(")
            .Append(string.Join(", ", parts))
            .Append("),\n                }");
    }

    /// <summary>
    /// The setter for one member, or the word for "this one cannot be written".
    /// </summary>
    /// <remarks>
    /// Read, modify, write back, through the member itself. A property that clamps what it is
    /// given, or keeps two fields in step, does that here exactly as it would anywhere else, which
    /// is the whole reason a property is described rather than the fields behind it. A property
    /// with no setter has nothing to emit and says so with a null.
    /// </remarks>
    private static string Writer(BehaviorModel model, BehaviorField field)
    {
        if (field.IsProperty && field.Hints.ReadOnly) return ",\n                    null";

        return ",\n"
            + "                    static (world, entity, value) =>\n"
            + "                    {\n"
            + "                        if (!world.TryGet<" + model.QualifiedName
            + ">(entity, out var component)) return false;\n"
            + "                        if (!global::Bevy.ComponentSchemas.TryCoerce<"
            + field.Type + ">(value, out var coerced)) return false;\n\n"
            + "                        component." + field.Name + " = coerced;\n"
            + "                        world.Set(entity, component);\n"
            + "                        return true;\n"
            + "                    }";
    }

    /// <summary>The name Bevy knows the component by, which is its CLR full name.</summary>
    private static string FullName(BehaviorModel model) =>
        model.Namespace is null ? model.Name : model.Namespace + "." + model.Name;

    /// <summary>The type as a tool should show it: no <c>global::</c>, no namespace.</summary>
    private static string Display(string qualified)
    {
        var name = qualified.StartsWith("global::", System.StringComparison.Ordinal)
            ? qualified.Substring("global::".Length)
            : qualified;

        var dot = name.LastIndexOf('.');
        return dot < 0 ? name : name.Substring(dot + 1);
    }

    /// <summary>The name of the factory method for one behavior's schema.</summary>
    private static string SchemaMethodName(BehaviorModel model) => "Describe_" + model.UniqueKey;
}
