using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Bevy.Generator;

/// <summary>
/// Writes the field tables that let a tool show a component it has never heard of.
/// </summary>
/// <remarks>
/// <para>
/// The bridge answers what an entity carries in component ids, and can name one, but a name is
/// not enough to draw a row: that needs the fields, their types, and a way to read and write
/// them. None of that has to cross the ABI, because a <c>[Behavior]</c> struct is a C# type this
/// generator is already reading. So the field table is emitted here, beside the runner, and the
/// engine stays out of it entirely.
/// </para>
/// <para>
/// Accessors rather than byte offsets: the emitted closure reads and writes the real struct
/// through the ordinary typed API, which means the runtime's own layout decisions cannot be got
/// wrong, and change detection fires exactly as it would for a behavior writing its own field.
/// </para>
/// </remarks>
internal static class SchemaEmitter
{
    private const string Header =
        "// <auto-generated by BevyCSharp.Generator />\n"
        + "#nullable enable\n"
        + "#pragma warning disable CS1591\n";

    /// <summary>Emits the per-assembly schema registration, or null when there is nothing to say.</summary>
    internal static string? Emit(IReadOnlyList<BehaviorModel> models)
    {
        var described = models
            .Where(model => model.Fields.Count > 0)
            .OrderBy(model => model.QualifiedName, System.StringComparer.Ordinal)
            .ToList();

        if (described.Count == 0) return null;

        var source = new StringBuilder(Header)
            .Append("\nnamespace Bevy.Generated;\n\n")
            .Append("/// <summary>Describes this assembly's behaviors to anything inspecting them.</summary>\n")
            .Append("internal static class ComponentSchemaRegistration\n")
            .Append("{\n")
            .Append("    /// <summary>\n")
            .Append("    /// Registers the field tables as soon as the CLR touches this assembly, so a\n")
            .Append("    /// tool can describe a component without the assembly having been asked to.\n")
            .Append("    /// </summary>\n")
            .Append("    [global::System.Runtime.CompilerServices.ModuleInitializer]\n")
            .Append("    internal static void Initialize()\n")
            .Append("    {\n");

        foreach (var model in described)
        {
            source.Append("        global::Bevy.ComponentSchemas.Add(")
                .Append(SchemaMethodName(model)).Append("());\n");
        }

        source.Append("    }\n");

        foreach (var model in described)
        {
            source.Append('\n');
            EmitSchema(source, model);
        }

        source.Append("}\n");
        return source.ToString();
    }

    /// <summary>Emits the factory for one behavior's schema.</summary>
    private static void EmitSchema(StringBuilder source, BehaviorModel model)
    {
        source.Append("    /// <summary>The fields of <see cref=\"").Append(model.QualifiedName)
            .Append("\"/>.</summary>\n")
            .Append("    private static global::Bevy.ComponentSchema ")
            .Append(SchemaMethodName(model)).Append("()\n")
            .Append("        => new(\n")
            .Append("            \"").Append(model.Name).Append("\",\n")
            .Append("            \"").Append(FullName(model)).Append("\",\n")
            .Append("            static () => global::Bevy.ComponentType<")
            .Append(model.QualifiedName).Append(">.Id,\n")
            .Append("            [\n");

        foreach (var field in model.Fields)
            EmitField(source, model, field);

        source.Append("            ]);\n");
    }

    /// <summary>Emits one field, with the pair of closures that reach the live component.</summary>
    private static void EmitField(StringBuilder source, BehaviorModel model, BehaviorField field)
    {
        source.Append("                new(\n")
            .Append("                    \"").Append(field.Name).Append("\",\n")
            .Append("                    global::Bevy.FieldKind.").Append(field.Kind).Append(",\n")
            .Append("                    \"").Append(Display(field.Type)).Append("\",\n")
            // Read: absent component reads as null, which is what a tool draws as a blank row
            // rather than as a zero it might then write back.
            .Append("                    static (world, entity) =>\n")
            .Append("                        world.TryGet<").Append(model.QualifiedName)
            .Append(">(entity, out var component) ? component.").Append(field.Name)
            .Append(" : null,\n")
            // Write: read, modify, write back. Going through Set rather than a reference into
            // storage is what makes Bevy see the change.
            .Append("                    static (world, entity, value) =>\n")
            .Append("                    {\n")
            .Append("                        if (!world.TryGet<").Append(model.QualifiedName)
            .Append(">(entity, out var component)) return false;\n")
            .Append("                        if (!global::Bevy.ComponentSchemas.TryCoerce<")
            .Append(field.Type).Append(">(value, out var coerced)) return false;\n\n")
            .Append("                        component.").Append(field.Name).Append(" = coerced;\n")
            .Append("                        world.Set(entity, component);\n")
            .Append("                        return true;\n")
            .Append("                    }");

        if (field.Options.Items.Count > 0)
        {
            source.Append(",\n                    [");
            var first = true;
            foreach (var option in field.Options.Items)
            {
                if (!first) source.Append(", ");
                source.Append('"').Append(option).Append('"');
                first = false;
            }

            source.Append(']');
        }

        source.Append("),\n");
    }

    /// <summary>The name Bevy knows the component by, which is its CLR full name.</summary>
    private static string FullName(BehaviorModel model) =>
        model.Namespace is null ? model.Name : model.Namespace + "." + model.Name;

    /// <summary>The type as a tool should show it: no <c>global::</c>, no namespace.</summary>
    private static string Display(string qualified)
    {
        var name = qualified.StartsWith("global::", System.StringComparison.Ordinal)
            ? qualified.Substring("global::".Length)
            : qualified;

        var dot = name.LastIndexOf('.');
        return dot < 0 ? name : name.Substring(dot + 1);
    }

    /// <summary>The name of the factory method for one behavior's schema.</summary>
    private static string SchemaMethodName(BehaviorModel model) => "Describe_" + model.UniqueKey;
}
