using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Bevy.Generator;

/// <summary>
/// Turns <c>[InitialState]</c> enums into state declarations an app adds by itself.
/// </summary>
/// <remarks>
/// A state declared on its enum, rather than added in a <c>Program.cs</c>, is how a behavior script
/// says what states it has, since the script is compiled by whichever host runs it and has no
/// program of its own. Found at compile time and declared from a module initializer, so the
/// declaration exists as soon as the assembly does and nothing reflects to find it, as for the
/// commands and schemas beside it.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class StateGenerator : IIncrementalGenerator
{
    private const string InitialStateAttribute = RecognizedAttributes.Namespace + "." + RecognizedAttributes.InitialState;

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var states = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                InitialStateAttribute,
                predicate: static (node, _) => node is EnumDeclarationSyntax,
                transform: static (ctx, _) => Extract(ctx))
            .Where(static state => state is not null)
            .Collect();

        context.RegisterSourceOutput(states, static (spc, found) =>
        {
            var models = found.Where(state => state is not null).Select(state => state!).ToList();
            if (models.Count == 0) return;

            spc.AddSource("StateDeclarations.g.cs", Emit(models));
        });
    }

    /// <summary>One declared state, by its enum's full name and the number it starts at.</summary>
    private sealed record StateModel(string Type, string Initial);

    private static StateModel? Extract(GeneratorAttributeSyntaxContext context)
    {
        if (context.TargetSymbol is not INamedTypeSymbol type || type.TypeKind != TypeKind.Enum) return null;

        var attribute = context.Attributes.FirstOrDefault();
        if (attribute is null || attribute.ConstructorArguments.Length != 1) return null;

        // An enum constant passed as an object arrives as its number, which is cast back to the
        // enum in what is emitted, so the declaration names the value and not a field of it.
        var value = attribute.ConstructorArguments[0].Value;
        if (value is null) return null;

        var full = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        return new StateModel(full, $"({full})({System.Convert.ToInt64(value, System.Globalization.CultureInfo.InvariantCulture)})");
    }

    private static string Emit(List<StateModel> models)
    {
        var source = new StringBuilder(1024);

        source.Append("// <auto-generated />\n")
            .Append("#nullable enable\n\n")
            .Append("namespace Bevy.Generated;\n\n")
            .Append("/// <summary>The states this assembly declares on their enums.</summary>\n")
            .Append("internal static class StateDeclarations\n")
            .Append("{\n")
            .Append("    /// <summary>Declares them as soon as the CLR touches this assembly.</summary>\n")
            .Append("    [global::System.Runtime.CompilerServices.ModuleInitializer]\n")
            .Append("    internal static void Initialize()\n")
            .Append("    {\n");

        foreach (var model in models.OrderBy(state => state.Type, System.StringComparer.Ordinal))
            source.Append("        global::Bevy.StateRegistry.Declare<").Append(model.Type).Append(">(").Append(model.Initial).Append(");\n");

        source.Append("    }\n")
            .Append("}\n");

        return source.ToString();
    }
}
